version: '3.8'

services:
  gbm-app:
    build: .
    container_name: gbm-presentation
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
