version: '3.8'

services:
  gbm-app-usa:
    build: .
    container_name: gbm-presentation-usa
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gbm-presentation-usa.rule=Host(`presentationusa.glaringmaintenance.com`)"
      - "traefik.http.routers.gbm-presentation-usa.entrypoints=websecure"
      - "traefik.http.routers.gbm-presentation-usa.tls=true"
      - "traefik.http.routers.gbm-presentation-usa.tls.certresolver=letsencrypt"
      - "traefik.http.services.gbm-presentation-usa.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
